### PR TITLE
fix #901 add some to all optics

### LINKED ISSUE #901: Add `some` method to all optics
I think this case is so common that it is worth the cost of a helper method.

Instead of `optic composePrism some`, user could do `optic.some`

What do you think?

### PR DESCRIPTION
**Pull request by julien-truffaut**

### CODE REVIEW

**Review by cquiroz — APPROVED** [review]
Looks great, we should release this soon

**Comment by julien-truffaut** [comment]
> Looks great, we should release this soon

We also need to fix the release :(

**Comment by julien-truffaut** [comment]
It also doesn't seem to be working for Scala 2.12

**Comment by julien-truffaut** [comment]
`substituteCo` is not available in 2.12, I tried to use `asInstanceOf` but I get the following error for 2.13:

```scala
[error] /Users/julien/project/Monocle/test/shared/src/test/scala/monocle/LensSpec.scala:105:25: Cannot prove that Option[Int] =:= Option[A1].
[error]     obj.applyLens(lens).some.getOption shouldEqual Some(2)
```

So it looks this can only work for Scala 2.13 :(

**Comment by cquiroz** [comment]
We could keep it as a 2.13 only. There are split dirs for 2.12/2.13

**Comment by julien-truffaut** [comment]
> We could keep it as a 2.13 only. There are split dirs for 2.12/2.13

Good idea, but I am not sure how to implement it because it needs to be a method in the optics class.

**Comment by julien-truffaut** [comment]
If there is no easy workaround, I would rather bump the major version and drop Scala 2.12 from the build. WDYT @cquiroz ?
We can always support bug fix the current major version.

**Comment by cquiroz** [comment]
I think it would be fine to drop 2.12, people on 2.12 can still use the older version

**Pull request merged**
