### PR TITLE
enable scalajs-mapSourceURI option if Scala 3

### PR DESCRIPTION
**Pull request by xuwei-k**
https://github.com/lampepfl/dotty/commit/c9533da391b8511c8aaca17b498a03b18ec6b3a8

### CODE REVIEW

**Comment by julien-truffaut** [comment]
Hi @xuwei-k sorry I missed your PR. We merged this one today, I have the feeling it does the same thing, is it correct?

https://github.com/optics-dev/Monocle/pull/1108/files

**Comment by xuwei-k** [comment]
I think not same thing

**Review by julien-truffaut — APPROVED** [review]
LGTM

**Comment by julien-truffaut** [comment]
Sorry I missed that thanks!

**Pull request merged**
