### PR TITLE
add orElse on Optional

### PR DESCRIPTION
**Pull request by julien-truffaut**

### CODE REVIEW

**Comment by julien-truffaut** [comment]
fix #1020

**Comment by julien-truffaut** [comment]
I think I found an example where this would break the law. I will add some doc next week.

**Comment by julien-truffaut** [comment]
Actually no, the example I had in mind is lawful. 

@kenbot @cquiroz would you mind to review this

**Review by cquiroz — APPROVED** [review]
Looks great

**Pull request merged**
