### PR TITLE
add test suite to check when composition works or not

### PR DESCRIPTION
**Pull request by julien-truffaut**
`CompositionGenericOpticsTest` make me think we should still offer non-overloaded compose methods.

We could add `andThenLens`, `andThenOptional`, ... but recommend to use them only when facing type inference issue which should hopefully be rare.

### CODE REVIEW

**Comment by yilinwei** [comment]
This will break once inheritance is added right? (the subclass would be valid).

**Comment by julien-truffaut** [comment]
@yilinwei What would break? I think we should postpone the decision on keeping non-overloaded method once we see the impact of inheritance + variance in Scala 2 and 3.

**Comment by yilinwei** [comment]
Sorry, "breaks" is the wrong word. Let me be a bit more specific; if the return type of the composition is a sub-type the test still works. I wonder if this form is better so it doesn't pass even if the sub-type is returned.

```scala
sealed trait Foo

trait Bar extends Foo
trait Baz extends Bar

object Bar {
  def apply(): Bar = ???
}

sealed trait ¬[A]

sealed trait NotLowPriority {
  given notambig[A]: ¬[A]  = ???
}

object ¬ extends NotLowPriority {
  given ambig1 [A](using a: A): ¬[A] = ???
  given ambig2 [A](using a: A): ¬[A] = ???
}


object Test {
  val optic = Bar()
  summon[optic.type <:< Bar]
  summon[¬[optic.type <:< Baz]]
}
```

**Comment by julien-truffaut** [comment]
I added thoses tests directly to #1088

**Pull request closed without merging**
