### PR TITLE
Replace atOrElse by withDefault syntax on optics

### PR DESCRIPTION
**Pull request by julien-truffaut**
The two most common operations on optics that point to an `Option` are:
1. focus only on `Some` which we can do with `some`
1. focus on `Some` or replace `None` by some default value

I propose to add `withDefault` method to all optics and apply optics similar to what we've done for `some`.
I removed `atOrElse`, it can easily be achieved by `at(x).withDefault(y)`

Main questions:
1. Is this use case worth the maintenace cost?
1. shall we add syntax for monorphic optics somewhere else? `implicit evTS: T =:= S, evBA: B =:= A, evOpt: A =:= Option[A1]` is not really readable.

### CODE REVIEW

**Comment by yilinwei** [comment]
@julien-truffaut Regarding the second point - does IntelliJ filter out such methods?

**Comment by julien-truffaut** [comment]
> @julien-truffaut Regarding the second point - does IntelliJ filter out such methods?

No, IntelliJ offers the method but there is s red squiggly
Screenshot 2020-10-14 at 09 40 25
Screenshot 2020-10-14 at 09 40 44

**Comment by julien-truffaut** [comment]
@yilinwei what do you think of this encoding?

**Comment by cquiroz** [comment]
I like this a lot. It is something I use all the time and would benefit from some syntax improvements.

**Comment by julien-truffaut** [comment]
If you are fine with this, I would prefer to merge this PR first before implementing the same syntax class for `Apply` optics. I prefer to do it in two or more PR as I would like to split each `Apply` optics in a separate class.

**Review by yilinwei — APPROVED** [review]

**Pull request merged**
