### PR TITLE
Deprecate FieldX for At with a singleton index

### PR DESCRIPTION
**Pull request by julien-truffaut**
Thanks to @nafg for the idea! see #957 

If we like the idea, I would like to:
1. deprecate `First`, `Second`, etc
1. generate At instances for more tuples. Where shall we stop?

### CODE REVIEW

**Comment by julien-truffaut** [comment]
The problem with this approach is that when we use `at("Hello")` the compiler believes that we want to use the singleton type "Hello".

**Comment by joroKr21** [comment]
You could constrain it to `Int with Singleton` but you would still have the same problem ambiguity with `at(2)`

**Comment by julien-truffaut** [comment]
> You could constrain it to `Int with Singleton` but you would still have the same ambiguity problem with `at(2)`

Where would you add this constraint? I guess what we need is a way to say try it with a singleton and if it doesn't work, try with a normal type (not sure about the terminology).

**Review by cquiroz — APPROVED** [review]
Looks great 👍

**Comment by yilinwei** [comment]
> Where would you add this constraint? I guess what we need is a way to say try it with a singleton and if it doesn't work, try with a normal type (not sure about the terminology).

@julien-truffaut, did you find a way around this issue?

**Comment by julien-truffaut** [comment]
@yilinwei I didn't but @joroKr21 did! See https://github.com/optics-dev/Monocle/pull/973

**Review by yilinwei — APPROVED** [review]

**Comment by julien-truffaut** [comment]
I just thought about something ... What will be the impact for the implicit resolution of `At`? I believe I read the algorithm that find implicit values is `O(n!)` where `n` is the number of instances. If that's the case, is it a bad idea to define all these instances?

**Comment by joroKr21** [comment]
I don't think it's that bad. Most instances will be filtered out by the `S` type parameter. And implicit search is not so slow in newer Scala versions. It's a funny story, the biggest slowdown was coming from creating error messages that were never shown 🙈 but I don't want to dig now for the `scalac` PR that fixed it.

**Pull request merged**
